### ISSUE TITLE
Pod hang in Pending state 

### ISSUE THREAD

**Issue by zackliu** [Azure/aci-connector-k8s#17] opened 2017-07-31 09:10 UTC
I just try the sample and the Pod `nginx` hang in Pending state.
The states of node and pod shows below. 

**Node**
> Name:                   aci-connector
> Role:
> Labels:                 <none>
> Annotations:            node.alpha.kubernetes.io/ttl=0
> Taints:                 azure.com/aci:NoSchedule
> CreationTimestamp:      Mon, 31 Jul 2017 17:02:26 +0800
> Conditions:
>   Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
>   ----                  ------  -----------------                       ------------------                      ------                          -------
>   Ready                 True    Mon, 31 Jul 2017 17:07:45 +0800         Mon, 31 Jul 2017 17:02:26 +0800         KubeletReady                    kubelet is posting ready
>   OutOfDisk             False   Mon, 31 Jul 2017 17:07:45 +0800         Mon, 31 Jul 2017 17:02:26 +0800         KubeletHasSufficientDisk        kubelet has sufficient disk space available
>   NetworkUnavailable    True    Mon, 31 Jul 2017 17:07:45 +0800         Mon, 31 Jul 2017 17:07:45 +0800         NoRouteCreated                  RouteController failed to create a route
> Addresses:
> Capacity:
>  cpu:           20
>  memory:        100Gi
>  pods:          20
> Allocatable:
>  cpu:           20
>  memory:        100Gi
>  pods:          20
> System Info:
>  Machine ID:
>  System UUID:
>  Boot ID:
>  Kernel Version:
>  OS Image:
>  Operating System:
>  Architecture:                  amd64
>  Container Runtime Version:
>  Kubelet Version:               1.6.6
>  Kube-Proxy Version:
> PodCIDR:                        10.244.2.0/24
> ExternalID:                     aci-connector
> Non-terminated Pods:            (1 in total)
>   Namespace                     Name            CPU Requests    CPU Limits      Memory Requests Memory Limits
>   ---------                     ----            ------------    ----------      --------------- -------------
>   default                       nginx           0 (0%)          0 (0%)          0 (0%)          0 (0%)
> Allocated resources:
>   (Total limits may be over 100 percent, i.e., overcommitted.)
>   CPU Requests  CPU Limits      Memory Requests Memory Limits
>   ------------  ----------      --------------- -------------
>   0 (0%)        0 (0%)          0 (0%)          0 (0%)
> Events:         <none>

**Pod**
> Name:           nginx
> Namespace:      default
> Node:           aci-connector/
> Labels:         <none>
> Annotations:    <none>
> Status:         Pending
> IP:
> Containers:
>   nginx:
>     Image:              nginx
>     Port:               <none>
>     Environment:        <none>
>     Mounts:
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-870nn (ro)
> Volumes:
>   default-token-870nn:
>     Type:       Secret (a volume populated by a Secret)
>     SecretName: default-token-870nn
>     Optional:   false
> QoS Class:      BestEffort
> Node-Selectors: <none>
> Tolerations:    <none>
> Events:         <none>

**kubectl logs aci-connector**

> { Error: The resource namespace 'Microsoft.Container' is invalid.
>     at client.pipeline (/app/node_modules/azure-arm-resource/lib/resource/operations/resources.js:1768:19)
>     at retryCallback (/app/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
>     at retryCallback (/app/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
>     at handleRedirect (/app/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
>     at /app/node_modules/ms-rest-azure/lib/filters/rpRegistrationFilter.js:59:14
>     at Request.defaultRequest [as _callback] (/app/node_modules/ms-rest/lib/requestPipeline.js:125:16)
>     at Request.self.callback (/app/node_modules/request/request.js:188:22)
>     at emitTwo (events.js:125:13)
>     at Request.emit (events.js:213:7)
>     at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
>     at emitOne (events.js:120:20)
>     at Request.emit (events.js:210:7)
>     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
>     at Object.onceWrapper (events.js:314:30)
>     at emitNone (events.js:110:20)
>     at IncomingMessage.emit (events.js:207:7)
>   statusCode: 404,
>   request:
>    { rawResponse: false,
>      queryString: {},
>      url: 'https://management.azure.com/subscriptions/1c5b82ee-9294-4568-b0c0-b9c523bc0d86/resourcegroups/aci/providers/Microsoft.Container//containerGroups/nginx?api-version=2017-04-01-preview',
>      method: 'PUT',
>      headers:
>       { 'x-ms-client-request-id': '9a2bd2ac-df9d-4200-b9a7-98997a574c18',
>         'accept-language': 'en-US',
>         'Content-Type': 'application/json; charset=utf-8',
>         'user-agent': 'Node/v8.1.2 (x64-Linux-4.4.0-87-generic) ms-rest/2.2.1 ms-rest-azure/2.2.3 azure-arm-resource/2.0.0-preview Azure-SDK-For-Node' },
>      body: '{"location":"westus","tags":{"orchestrator":"kubernetes"},"properties":{"osType":"linux","containers":[{"name":"nginx","properties":{"ports":[{"port":80}],"image":"nginx"}}],"ipAddress":{"type":"Public","ports":[{"protocol":"TCP","port":80}]}}}' },
>   response:
>    { body: '{"error":{"code":"InvalidResourceNamespace","message":"The resource namespace \'Microsoft.Container\' is invalid."}}',
>      headers:
>       { 'cache-control': 'no-cache',
>         pragma: 'no-cache',
>         'content-type': 'application/json; charset=utf-8',
>         expires: '-1',
>         'x-ms-failure-cause': 'gateway',
>         'x-ms-request-id': '52ab5a6d-94c0-4630-8cd6-733678afaf6b',
>         'x-ms-correlation-request-id': '52ab5a6d-94c0-4630-8cd6-733678afaf6b',
>         'x-ms-routing-request-id': 'EASTUS:20170731T093737Z:52ab5a6d-94c0-4630-8cd6-733678afaf6b',
>         'strict-transport-security': 'max-age=31536000; includeSubDomains',
>         date: 'Mon, 31 Jul 2017 09:37:37 GMT',
>         connection: 'close',
>         'content-length': '114' },
>      statusCode: 404 },
>   code: 'InvalidResourceNamespace',
>   body:
>    { code: 'InvalidResourceNamespace',
>      message: 'The resource namespace \'Microsoft.Container\' is invalid.' } }
> container deleter
> sending update.
> container deleter
> k8s pod creater/updater
> container deleter

**Comment by julianfrank** [comment] 2017-07-31 10:32
I'm having the exact same problem... I tried with a local minikube on Ubuntu 16.04 implemented locally

**Comment by vladfr** [comment] 2017-07-31 12:06
Getting the same thing

**Comment by vladfr** [comment] 2017-07-31 12:24
This is fixed by PR #9.

As a temp workaround you can edit aci-connector.yaml and replace the image with shibayan/aci-connector-k8s which has the correct resource configs - confirmed working.

**Comment by zackliu** [comment] 2017-08-01 01:44
@vladfr Thanks a lot, resolved.

**Comment by seanmck** [comment] 2017-08-04 22:22
I've pushed an updated image to the microsoft account, so this should be fixed.

**Closed by seanmck** 2017-08-04 22:22 UTC

**Comment by julianfrank** [comment] 2017-08-05 10:30
I can confirm it works perfectly now :+1:

**Comment by ThorstenHans** [comment] 2017-08-24 06:44
Ran into the same issue but had a different root cause.

On my Azure subscription, `Microsoft.ContainerInstance` wasn't registered in the providers list, I'd to execute `az provider register -n Microsoft.ContainerInstance` first
